Projects pop up
phelian23/My-portfolio pull request #12
Opened 2021-10-06 13:53 UTC by phelian23

Add pop up to project to show project details when the button is clicked

2021-10-06 15:00 UTC, mke2111 requested changes
### Hey @phelian23, 

**This is a great project you have going on, well-done lad**. 

   
**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

## Required Changes ♻️
_Check the inline comments under the review for sections to improve._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-06 15:04 UTC, mke2111 commented on script.js
> +};
- [ ] The pop-up should be responsive for both mobile and desktop screens.
![Screenshot from 2021-10-06 18-02-34](https://user-images.githubusercontent.com/65501535/136230304-376d710c-2aa1-4349-9019-ad1ae58575df.png)
![Screenshot from 2021-10-06 18-03-58](https://user-images.githubusercontent.com/65501535/136230543-249c8169-1c29-4ed9-a759-6e3af6fe0680.png)

2021-10-06 15:12 UTC, mke2111 commented on script.js
> +  });
- [ ] For this project, the JavaScript code should implement an array of objects to store JavaScript objects containing the information for each project.
- [ ] The above requirements means that the projects section is created dynamically with the information from the projects array (all the HTML of the section is created when the page loads). **This requires changes in existing code - already created HTML code for projects list should be removed and instead it should be added via JavaScript**. 
- [ ] Modal popup data is populated with the data from the projects array.
- [ ] All these requirements will make adding projects in the future easy. You will only add it in one place - as another object in the projects array.

2021-10-06 15:13 UTC, mke2111 commented on index.html
> +                        <li><p class="language1">html</p></li>
- [ ] For this milestone, projects are displayed dynamically using javascript code, remove all code for all projects in the html file.

2021-10-06 15:15 UTC, mke2111 commented on script.js
> +  btnImg2.classList.add('btn-img');
OPTIONAL

- [ ] I strongly suggest that your DOM manipulation should be handled in a separate module since dealing with DOM is usually expensive. Create another file and add the DOM code.

2021-10-07 15:22 UTC, dasileker approved these changes
### **Hi  @phelian23,** 

### **Congratulations! 🎉 Project Approved ✅**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 

![Approved](https://user-images.githubusercontent.com/61562626/136414717-61addff9-a006-4226-8d9c-40dbc9c85136.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-07 15:23 UTC, merged