Work section and About Section
phelian23/My-portfolio pull request #2
Opened 2021-09-17 21:53 UTC by phelian23

Add mobile version work section and about section

2021-09-17 22:38 UTC, ZeenatLawal requested changes
Hi @phelian23, 

Great job so far!:clap: :clap:
## To Highlight 🎊 🎊 
- GitHub flow is followed. ✔️
- PR has a title and summary. ✔️

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-17 22:38 UTC, ZeenatLawal commented on index.html
> +            <p class="workhead2">My Recent Works</p>
- [ ] The title (My Recent Works) should use a header tag(e.g. `h2`, `h3`, `h4`) as defined in the design

2021-09-17 22:38 UTC, ZeenatLawal commented on index.html
> +                    </ul>
- [ ] The title for each project card should use a header tag(e.g. `h2`, `h3`, `h4`) instead of `p` as stated in the requirements

2021-09-17 22:38 UTC, ZeenatLawal commented on index.html
> +            </div>
- [ ] The See Project buttons in this section should follow the button styling: Active, Hover and Pressed (see design)

2021-09-17 22:38 UTC, ZeenatLawal commented on index.html
> +                <img class="abtimg1" src="Images/Group(1).png" alt="About image">
- [ ] The section should have a proper background image, the decorations should be background images, not `img` tags

2021-09-17 22:38 UTC, ZeenatLawal commented on index.html
> +                <button type="button">Get My Resume</button>
- [ ] The Get My Resume button should follow the button styling: Active, Hover and Pressed (see design)

2021-09-17 22:38 UTC, ZeenatLawal commented on index.html
> +            </div>
- [ ] Kindly make sure this section has similar margins (top, bottom, left, right) as defined in the design

2021-09-17 22:38 UTC, ZeenatLawal commented on index.html
> +        </section>
- [ ] Kindly make sure this section has similar margins (top, bottom, left, right) as defined in the design

2021-09-18 10:37 UTC, Mihndim2020 approved these changes
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
Hi @phelian23 , 

Your project is complete! Great work on making the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

![Congratulations-Memes-FEATURED](https://user-images.githubusercontent.com/65852621/133696300-b506e476-dc1a-443e-935a-c6f434e788b6.jpg)

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-18 10:45 UTC, merged