Form
phelian23/My-portfolio pull request #3
Opened 2021-09-21 15:53 UTC by phelian23

Add a contact form to the mobile version

2021-09-21 16:57 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️ 

Hi @phelian23 and @Chimwemwe-127001,

Good job so far!
- You have done great with the design
- Your linters are working properly.
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ]  Please fix your background color. It is different from what is on the [Figma template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471)

**Figma template:**
![phels-orig](https://user-images.githubusercontent.com/36542986/134213996-025f4075-84d3-4755-891d-c8a979581733.PNG)

**Your design:**
![phels-new](https://user-images.githubusercontent.com/36542986/134214086-07485bb6-eeee-4b23-ac9f-6ee517b8077c.PNG)

- [ ] **_Check the comments under the review._**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-21 16:57 UTC, TedLivist commented on index.html
>              <form>
Your form should submit properly using the [Formspree service](https://formspree.io/html) as required in the description.
- [ ] The action value should be similar to https://formspree.io/f/{form_id}
- [ ] method value equals POST

2021-09-21 16:57 UTC, TedLivist commented on index.html
>              <form>
Your form should submit using the [Formspree service](https://formspree.io/html) as required in the description.
- [ ] `action` value should be similar to `https://formspree.io/f/{form_id}`
- [ ] `method` value equals `POST`

2021-09-21 16:57 UTC, TedLivist commented on index.html
> +                <textarea class="note" placeholder="Hello Femi. Glad to see you!" maxlength="500"></textarea><br>
- [ ] Please all inputs should have the `required` attribute to activate the validation on submit.

2021-09-21 16:57 UTC, TedLivist commented on index.html
> +
- [ ] Please remove the blank line as it is unnecessary

![blank_m](https://user-images.githubusercontent.com/36542986/134212911-e5cfd51c-d52c-456a-9e12-d7d4fa9d3670.jpg)

2021-09-21 16:57 UTC, TedLivist commented on index.html
>              </div>
- [ ] Please fix your indentation. `<form>` element should be indented.

2021-09-22 06:25 UTC, phelian23 commented
Thanks for the review. for the color difference in the form section, I don't know what's the cause, because I used the exact color code in the template

2021-09-22 06:49 UTC, emmanuellekamwa approved these changes
**STATUS: APPROVED ✔🎉**
Hello @phelian23 👋🏽
Your project is complete!  There is nothing else to say. It's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-22 06:59 UTC, merged